
/*
 * 
 */

package tw.com.hyweb.starbucks.wstest.querybonus.gen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Jul 29 14:20:57 CST 2013
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "QueryBonusService", 
                  wsdlLocation = "file:QueryBonusService.wsdl",
                  targetNamespace = "http://querybonus.ws.starbucks.hyweb.com.tw/") 
public class QueryBonusService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://querybonus.ws.starbucks.hyweb.com.tw/", "QueryBonusService");
    public final static QName QueryBonusServiceJobPort = new QName("http://querybonus.ws.starbucks.hyweb.com.tw/", "QueryBonusServiceJobPort");
    static {
        URL url = null;
        try {
            url = new URL("file:QueryBonusService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:QueryBonusService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public QueryBonusService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryBonusService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryBonusService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns QueryBonusService
     */
    @WebEndpoint(name = "QueryBonusServiceJobPort")
    public QueryBonusService getQueryBonusServiceJobPort() {
        return super.getPort(QueryBonusServiceJobPort, QueryBonusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryBonusService
     */
//    @WebEndpoint(name = "QueryBonusServiceJobPort")
//    public QueryBonusService getQueryBonusServiceJobPort(WebServiceFeature... features) {
//        return super.getPort(QueryBonusServiceJobPort, QueryBonusService.class, features);
//    }

}
