
package tw.com.hyweb.starbucks.wstest.cardlost.gen;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Sep 03 18:43:05 CST 2012
 * Generated source version: 2.2.4
 * 
 */

public final class CardLostService_CardLostServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cardLost.ws.starbucks.hyweb.com.tw/", "CardLostService");

    private CardLostService_CardLostServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CardLostService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CardLostService_Service ss = new CardLostService_Service(wsdlURL, SERVICE_NAME);
        CardLostService port = ss.getCardLostServiceImplPort();  
        
        {
        System.out.println("Invoking lost...");
        java.lang.String _lost_arg0 = "";
        java.lang.String _lost__return = port.lost(_lost_arg0);
        System.out.println("lost.result=" + _lost__return);


        }

        System.exit(0);
    }

}
