/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenTLVDialog.java
 *
 * Created on 2010/6/28, 下午 08:21:55
 */
package tw.com.hyweb.gui;

import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import tw.com.hyweb.iso.field.BerTLV;
import tw.com.hyweb.util.ISOUtil;

/**
 *
 * @author SamSon
 */
public class GenTLVDialog extends javax.swing.JDialog
{

    private BerTLV tlv;
    private static String[] items = new String[]
    {
        "4F",
        "5F2A",
        "71",
        "72",
        "82",
        "84",
        "91",
        "95",
        "9A",
        "9C",
        "9F02",
        "9F03",
        "9F09",
        "9F10",
        "9F1A",
        "9F1E",
        "9F26",
        "9F27",
        "9F33",
        "9F34",
        "9F35",
        "9F36",
        "9F37",
        "9F41",
        "9F53"
    };
    private static HashMap<String, Integer> mapTLV = new HashMap<String, Integer>();


    {
        mapTLV.put("9F02", 12);
        mapTLV.put("9F03", 12);
        mapTLV.put("9F1A", 4);//N3
        mapTLV.put("95", 10);//B
        mapTLV.put("5F2A", 4);//N3
        mapTLV.put("9A", 6);
        mapTLV.put("9C", 2);
        mapTLV.put("9F37", 8);//B
        mapTLV.put("82", 4);//B
        mapTLV.put("9F36", 4);//B
        mapTLV.put("D6", 8);//B
    }
    private JTable tbl;

    public GenTLVDialog(JTable tbl, java.awt.Frame parent, boolean modal)
    {
        this(parent, modal);
        this.tbl = tbl;
    }

    /** Creates new form GenTLVDialog */
    public GenTLVDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        for (int i = 0; i < items.length; i++)
        {
            jComboBox1.addItem(items[i]);
        }
        tlv = new BerTLV();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setEditable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Modify");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Del");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(166, 166, 166)
                .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .add(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2)
                    .add(jButton3)
                    .add(jButton1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        handleTLV('A');
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        handleTLV('U');
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        handleTLV('D');
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        int row = tbl.getEditingRow();
        String value = jTextArea1.getText();
        //tbl.setValueAt(value, row, SimTopPanel.TBL_VALUE);
        DefaultTableModel tblmodel = ((DefaultTableModel) tbl.getModel());
        tblmodel.setValueAt(value, row, SimTopPanel.TBL_VALUE);
        //tblmodel.fireTableCellUpdated(row, SimTopPanel.TBL_VALUE);
        System.out.println("row:[" + row + "] clo:[" + SimTopPanel.TBL_VALUE + "]" + tbl.getValueAt(row, SimTopPanel.TBL_VALUE));
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void handleTLV(char type)
    {
        JTextField tf = (JTextField) jComboBox1.getEditor().getEditorComponent();
        String tag = tf.getText();
        String value = jTextField1.getText();
        if (mapTLV.containsKey(tag))
        {
            int len = mapTLV.get(tag);
            if (value.length() != len)
            {
                String msg = "input length must = " + len;
                Toolkit.getDefaultToolkit().beep();
                tf.requestFocus();
                JOptionPane.showMessageDialog(null, msg, "Alert!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        switch (type)
        {
            case 'A':
            case 'U':
                tlv.addHexStr(tag, value);
                jTextArea1.setText(ISOUtil.hexString(tlv.pack()));
                break;
            case 'D':
                tlv.delByTag(tag);
                jTextArea1.setText(ISOUtil.hexString(tlv.pack()));
                break;
        }
        tf.setText(tf.getText().toUpperCase());
        jTextField1.setText("");
    }

    public String getReturnText()
    {
        return jTextArea1.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                GenTLVDialog dialog = new GenTLVDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
