package tw.com.hyweb.starbucks.wstest.balancetransfer.gen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Jul 24 09:40:17 CST 2013
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://balancetransfer.ws.starbucks.hyweb.com.tw/", name = "BalanceTransferService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BalanceTransferService {

    @WebResult(name = "return", targetNamespace = "http://balancetransfer.ws.starbucks.hyweb.com.tw/", partName = "return")
    @WebMethod
    public java.lang.String balanceTransfer(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
