
package tw.com.hyweb.starbucks.wstest.querytxn.gen;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.4
 * Fri Aug 31 16:33:09 CST 2012
 * Generated source version: 2.2.4
 * 
 */

public final class QueryTxnService_QueryTxnServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://querytxn.ws.starbucks.hyweb.com.tw/", "QueryTxnService");

    private QueryTxnService_QueryTxnServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = QueryTxnService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryTxnService_Service ss = new QueryTxnService_Service(wsdlURL, SERVICE_NAME);
        QueryTxnService port = ss.getQueryTxnServiceImplPort();  
        
        {
        System.out.println("Invoking queryTxn...");
        java.lang.String _queryTxn_arg0 = "";
        java.lang.String _queryTxn__return = port.queryTxn(_queryTxn_arg0);
        System.out.println("queryTxn.result=" + _queryTxn__return);


        }

        System.exit(0);
    }

}
