package tw.com.hyweb.starbucks.wstest.querybonus.gen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Jul 29 14:20:57 CST 2013
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://querybonus.ws.starbucks.hyweb.com.tw/", name = "QueryBonusService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface QueryBonusService {

    @WebResult(name = "return", targetNamespace = "http://querybonus.ws.starbucks.hyweb.com.tw/", partName = "return")
    @WebMethod
    public java.lang.String queryBonus(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
