package tw.com.hyweb.starbucks.wstest.cardlost.gen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Sep 03 18:43:05 CST 2012
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://cardLost.ws.starbucks.hyweb.com.tw/", name = "CardLostService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CardLostService {

    @WebResult(name = "return", targetNamespace = "http://cardLost.ws.starbucks.hyweb.com.tw/", partName = "return")
    @WebMethod
    public java.lang.String lost(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
